### ISSUE TITLE
How old is the OSM database replica?

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#187]
It is supposed to be "updated at one minute intervals", but it seems actually to be a few days late. Eg in http://export.hotosm.org/en/exports/d702396d-8ed0-4a4e-82b8-77c4fec16fdf/ it provides only 252 buildings vs the thousands traced since http://taches.francophonelibre.org/project/121 has been created.

**Comment by bdon** [comment]
Our overpass server has the updated buildings for this area, seems to be a duplicate of #181

**Comment by bdon** [comment]
@severinmenard I have fixed this and re-ran the export: http://export.hotosm.org/en/exports/d702396d-8ed0-4a4e-82b8-77c4fec16fdf/

Can you confirm that the result is as desired?

**Comment by severinmenard** [comment]
@bdon yes it works now, though it is not as close to the main database as it used to be: eg the last run at 10:28AM still does not show the edits of https://www.openstreetmap.org/changeset/49330120
The website should clearly show the time gap on the main page

**Comment by bdon** [comment]
@seveinmenard the timestamp of the last update is an addition to the new v3 export tool that's still in development.

However I just tested making a change and it showed up within 4-5 minutes. Functionally nothing has changed in export.hotosm.org that would make the results be more delayed than before. Can you double check with your next task that it doesn't show up within 10 minutes or so?
